[package]
name = "datasmith"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
alloy = { version = "0.9.2", features = ["full"] }
anyhow = "1.0.96"
tokio = "1.43.0"
